version: "3.3"
   
services:
  nemo:
    image: cjer/nemo
    build: .
    working_dir: /NEMO
    command: uvicorn api_main:app --port 8090 --host 0.0.0.0
    ports: 
      - "8090:8090"
    environment:
      - YAP_API_HOST=yap
      - YAP_API_PORT=8000
    depends_on:
      - yap
    networks:
      - devops
  yap:
    image: cjer/yap
    build: ./yap_docker
    working_dir: /yap/src/yap
    command: ./yap api
    healthcheck:
        test: ["CMD", "curl", "-s", "-X" ,"GET", "-H", "'Content-Type: application/json'", "-d'{\"text\": \"גנן גידל דגן בגן  \"}'", "localhost:8000/yap/heb/joint"]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
      - devops


networks:
        devops:
                external: true
# add this if you want yap available externally as well
#    ports: 
#      - "8000:8000"
