version: "3.3"
   

# If you want multiple NEMO instances, duplicate the nemo & yap services with different name, and remember to also use a different name for container_name of each NEMO instance.

services:
  nemo-1:
    image: cjer/nemo
    container_name: bullzai-nemo-1
    build: .
    working_dir: /NEMO
    command: uvicorn api_main:app --port 8090 --host 0.0.0.0
    ports: 
      - "8090:8090"
    environment:
      - YAP_API_HOST=yap-1
      - YAP_API_PORT=8000
    networks:
      - bullzai-infrastructure

  yap-1:
    image: cjer/yap
    build: ./yap_docker
    working_dir: /yap/src/yap
    command: ./yap api
    healthcheck:
        test: ["CMD", "curl", "-s", "-X" ,"GET", "-H", "'Content-Type: application/json'", "-d'{\"text\": \"גנן גידל דגן בגן  \"}'", "localhost:8000/yap/heb/joint"]
        interval: 30s
        timeout: 10s
        retries: 10
    networks:
      - bullzai-infrastructure


networks:
        bullzai-infrastructure:
                external: true
# add this if you want yap available externally as well
#    ports: 
#      - "8000:8000"
